# SPDX-FileCopyrightText: 2025 Eyad Issa <eyadlorenzo@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: almastudio
description: "An unoffical Flutter application to replace the MyUnibo app."
publish_to: "none"

version: "0.1.0"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  fl_chart: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
